"""
LifeSimulationPlugin - 事件及人体模拟插件（AI驱动版本）
Life Simulation Plugin (AI-Driven Version)

This plugin simulates human physiological states, daily activities, social behaviors,
and environmental awareness using AI-driven approach to make the bot more human-like.

Features:
- AI-driven schedule generation (work, leisure, meals, daily routine)
- AI-driven random event generation
- Health status determined by random events and schedule
- Habits from config or AI-generated based on personality
- Holiday API integration for dynamic holiday detection
- AI-driven emotion judgment
- Editable AI prompts with well-designed defaults
- Customizable time/date API
- Configurable AI models (tool_use, planner, replyer)

Key Design Principles:
- All dialogue is generated by AI, not fixed
- Physiological state data cannot be modified by commands
- AI makes decisions based on context, personality, and habits
- Prompts are loaded from config file, not hardcoded
"""

import asyncio
import json
import os
import random
from datetime import datetime, time, date
from enum import Enum
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
import aiohttp

from src.plugin_system import (
    BasePlugin,
    register_plugin,
    BaseCommand,
    BaseAction,
    BaseEventHandler,
    BaseTool,
    ComponentInfo,
    ConfigField,
    EventType,
    ActionActivationType,
    MaiMessages,
    ToolParamType,
    get_logger,
    llm_api,
    message_api,
    send_api,
)

logger = get_logger("life_simulation_plugin")

# Global plugin instance
_plugin_instance = None


# ============================================================
# Enums / 枚举定义
# ============================================================

class SleepState(Enum):
    """睡眠状态枚举 / Sleep State Enum"""
    AWAKE = "awake"
    SLEEPY = "sleepy"
    FALLING_ASLEEP = "falling_asleep"
    LIGHT_SLEEP = "light_sleep"
    DEEP_SLEEP = "deep_sleep"
    WAKING_UP = "waking_up"


class HealthStatus(Enum):
    """健康状态枚举 / Health Status Enum"""
    HEALTHY = "healthy"
    RECOVERING = "recovering"
    SLIGHTLY_ILL = "slightly_ill"
    ILL = "ill"
    SERIOUSLY_ILL = "seriously_ill"


# ============================================================
# State Management / 状态管理
# ============================================================

class LifeState:
    """生活状态类 / Life State Class"""

    def __init__(self):
        # Sleep state / 睡眠状态
        self.sleep_state: SleepState = SleepState.AWAKE
        self.last_sleep_time: float = 0.0
        self.last_wake_time: float = 0.0

        # Physiological states / 生理状态
        self.fatigue: int = 0  # 0-100
        self.hunger: int = 0  # 0-100
        self.health: int = 100  # 0-100
        self.health_status: HealthStatus = HealthStatus.HEALTHY

        # Emotion state / 情绪状态
        self.current_emotion: str = "calm"
        self.emotion_intensity: int = 0  # 0-100
        self.emotion_reason: str = ""

        # Activity state / 活动状态
        self.current_activity: str = "idle"
        self.current_activity_description: str = ""
        self.last_activity_time: float = 0.0

        # Schedule / 日程
        self.schedule: List[Dict[str, Any]] = []
        self.schedule_generated_date: str = ""

        # Habits / 习惯
        self.speaking_habits: List[str] = []
        self.behavior_habits: List[str] = []
        self.interests: List[str] = []
        self.preferences: Dict[str, str] = {}

        # Holidays / 节日
        self.current_holiday: str = ""
        self.is_holiday: bool = False
        self.holiday_cache: Dict[str, str] = {}
        self.last_holiday_check: float = 0.0

        # Update timestamp / 更新时间戳
        self.last_update: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        """转换为字典 / Convert to dictionary"""
        return {
            "sleep_state": self.sleep_state.value,
            "last_sleep_time": self.last_sleep_time,
            "last_wake_time": self.last_wake_time,
            "fatigue": self.fatigue,
            "hunger": self.hunger,
            "health": self.health,
            "health_status": self.health_status.value,
            "current_emotion": self.current_emotion,
            "emotion_intensity": self.emotion_intensity,
            "emotion_reason": self.emotion_reason,
            "current_activity": self.current_activity,
            "current_activity_description": self.current_activity_description,
            "last_activity_time": self.last_activity_time,
            "schedule": self.schedule,
            "schedule_generated_date": self.schedule_generated_date,
            "speaking_habits": self.speaking_habits,
            "behavior_habits": self.behavior_habits,
            "interests": self.interests,
            "preferences": self.preferences,
            "current_holiday": self.current_holiday,
            "is_holiday": self.is_holiday,
            "last_update": self.last_update,
        }

    def from_dict(self, data: Dict[str, Any]):
        """从字典加载 / Load from dictionary"""
        try:
            self.sleep_state = SleepState(data.get("sleep_state", SleepState.AWAKE.value))
            self.last_sleep_time = data.get("last_sleep_time", 0.0)
            self.last_wake_time = data.get("last_wake_time", 0.0)
            self.fatigue = data.get("fatigue", 0)
            self.hunger = data.get("hunger", 0)
            self.health = data.get("health", 100)
            self.health_status = HealthStatus(data.get("health_status", HealthStatus.HEALTHY.value))
            self.current_emotion = data.get("current_emotion", "calm")
            self.emotion_intensity = data.get("emotion_intensity", 0)
            self.emotion_reason = data.get("emotion_reason", "")
            self.current_activity = data.get("current_activity", "idle")
            self.current_activity_description = data.get("current_activity_description", "")
            self.last_activity_time = data.get("last_activity_time", 0.0)
            self.schedule = data.get("schedule", [])
            self.schedule_generated_date = data.get("schedule_generated_date", "")
            self.speaking_habits = data.get("speaking_habits", [])
            self.behavior_habits = data.get("behavior_habits", [])
            self.interests = data.get("interests", [])
            self.preferences = data.get("preferences", {})
            self.current_holiday = data.get("current_holiday", "")
            self.is_holiday = data.get("is_holiday", False)
            self.last_update = data.get("last_update", 0.0)
        except Exception as e:
            logger.error(f"Failed to load state from dict: {e}")


# ============================================================
# Time API / 时间API
# ============================================================

class TimeAPI:
    """时间API / Time API"""

    def __init__(self, config: Dict[str, Any]):
        self.method = config.get("method", "builtin")
        self.url = config.get("url", "")
        self.timeout = config.get("timeout", 5)

    async def get_current_time(self) -> datetime:
        """获取当前时间 / Get current time"""
        if self.method == "custom" and self.url:
            try:
                async with aiohttp.ClientSession() as session:
                    async with session.get(self.url, timeout=self.timeout) as response:
                        if response.status == 200:
                            data = await response.json()
                            # 尝试解析常见的datetime字段
                            if "datetime" in data:
                                return datetime.fromisoformat(data["datetime"].replace("Z", "+00:00"))
                            elif "unixtime" in data:
                                return datetime.fromtimestamp(data["unixtime"])
            except Exception as e:
                logger.warning(f"Failed to fetch time from custom API: {e}")

        # 默认使用内置datetime / Default to built-in datetime
        return datetime.now()


# ============================================================
# Holiday API / 节日API
# ============================================================

class HolidayAPI:
    """节日API / Holiday API"""

    def __init__(self, config: Dict[str, Any]):
        self.enabled = config.get("enabled", True)
        self.url_template = config.get("url", "https://timor.tech/api/holiday/info/{date}")
        self.cache_duration = config.get("cache_duration", 86400)
        self.timeout = config.get("timeout", 5)
        self.cache: Dict[str, str] = {}

    async def get_holiday(self, date_obj: date) -> Tuple[str, bool]:
        """获取节日信息 / Get holiday information"""
        if not self.enabled:
            return "", False

        date_str = date_obj.strftime("%Y-%m-%d")

        # Check cache / 检查缓存
        if date_str in self.cache:
            return self.cache[date_str], True

        # Use holiday API / 使用节日API
        try:
            url = self.url_template.replace("{date}", date_str)
            async with aiohttp.ClientSession() as session:
                async with session.get(url, timeout=self.timeout) as response:
                    if response.status == 200:
                        data = await response.json()
                        if data.get("code") == 0:
                            holiday = data.get("holiday", None)
                            if holiday:
                                holiday_name = holiday.get("name", "")
                                self.cache[date_str] = holiday_name
                                return holiday_name, True
        except Exception as e:
            logger.warning(f"Failed to fetch holiday info: {e}")

        # Check for common holidays manually / 手动检查常见节日
        holiday = self._check_common_holidays(date_obj)
        if holiday:
            self.cache[date_str] = holiday
            return holiday, True

        self.cache[date_str] = ""
        return "", False

    def _check_common_holidays(self, date_obj: date) -> str:
        """检查常见节日 / Check common holidays"""
        month = date_obj.month
        day = date_obj.day

        # Chinese holidays / 中国节日
        if month == 1 and day == 1:
            return "元旦"
        elif month == 2 and 14 <= day <= 20:  # Spring Festival (approximate)
            return "春节"
        elif month == 4 and 4 <= day <= 6:  # Qingming Festival
            return "清明节"
        elif month == 5 and 1 == day:
            return "劳动节"
        elif month == 6 and day in [22, 23]:  # Dragon Boat Festival (approximate)
            return "端午节"
        elif month == 10 and 1 == day:
            return "国庆节"

        # Western holidays / 西方节日
        elif month == 12 and 25 == day:
            return "圣诞节"
        elif month == 2 and 14 == day:
            return "情人节"

        return ""


# ============================================================
# Plugin Main Class / 插件主类
# ============================================================

@register_plugin
class LifeSimulationPlugin(BasePlugin):
    """事件及人体模拟插件 / Life Simulation Plugin"""

    plugin_name: str = "life_simulation_plugin"
    enable_plugin: bool = True
    config_file_name: str = "config.toml"
    dependencies: List[str] = []
    python_dependencies: List[Any] = []

    config_section_descriptions = {
        "plugin": "插件基础配置 / Basic Plugin Configuration",
        "ai": "AI模型配置 / AI Model Configuration",
        "prompts": "AI提示词配置 / AI Prompts Configuration",
        "habits": "习惯配置 / Habits Configuration",
        "schedule": "日程配置 / Schedule Configuration",
        "time_api": "时间日期API配置 / Time and Date API Configuration",
        "holiday_api": "节日API配置 / Holiday API Configuration",
        "commands": "命令配置 / Commands Configuration",
        "state": "状态配置 / State Configuration",
        "logging": "日志配置 / Logging Configuration",
    }

    config_schema: dict = {
        "plugin": {
            "enabled": ConfigField(type=bool, default=True, description="启用插件 / Enable plugin"),
            "update_interval": ConfigField(type=int, default=60, description="状态更新间隔（秒）/ State update interval (seconds)"),
            "data_dir": ConfigField(type=str, default="data", description="数据目录 / Data directory"),
        },
        "ai": {
            "schedule_model": ConfigField(
                type=str, 
                default="replyer", 
                description="日程生成模型 / Schedule generation model",
                choices=["tool_use", "planner", "replyer", "utils", "vlm", "voice", "embedding", "lpmm_entity_extract", "lpmm_rdf_build"]
            ),
            "event_model": ConfigField(
                type=str, 
                default="tool_use", 
                description="随机事件生成模型 / Random event generation model",
                choices=["tool_use", "planner", "replyer", "utils", "vlm", "voice", "embedding", "lpmm_entity_extract", "lpmm_rdf_build"]
            ),
            "emotion_model": ConfigField(
                type=str, 
                default="planner", 
                description="情绪判断模型 / Emotion judgment model",
                choices=["tool_use", "planner", "replyer", "utils", "vlm", "voice", "embedding", "lpmm_entity_extract", "lpmm_rdf_build"]
            ),
            "habit_model": ConfigField(
                type=str, 
                default="replyer", 
                description="习惯生成模型 / Habit generation model",
                choices=["tool_use", "planner", "replyer", "utils", "vlm", "voice", "embedding", "lpmm_entity_extract", "lpmm_rdf_build"]
            ),
            "temperature": ConfigField(type=float, default=0.7, description="AI温度 / AI temperature"),
            "max_tokens": ConfigField(type=int, default=1000, description="AI最大token数 / AI max tokens"),
        },
        "prompts": {
            "schedule_generation": ConfigField(type=str, default="", description="日程生成提示词 / Schedule generation prompt"),
            "random_event_generation": ConfigField(type=str, default="", description="随机事件生成提示词 / Random event generation prompt"),
            "emotion_judgment": ConfigField(type=str, default="", description="情绪判断提示词 / Emotion judgment prompt"),
            "habit_generation": ConfigField(type=str, default="", description="习惯生成提示词 / Habit generation prompt"),
        },
        "habits": {
            "use_ai_generation": ConfigField(type=bool, default=True, description="使用AI生成习惯 / Use AI to generate habits"),
            "speaking_habits": ConfigField(type=list, default=[], description="说话习惯 / Speaking habits"),
            "behavior_habits": ConfigField(type=list, default=[], description="行为习惯 / Behavior habits"),
            "interests": ConfigField(type=list, default=[], description="兴趣爱好 / Interests"),
        },
        "schedule": {
            "regenerate_daily": ConfigField(type=bool, default=True, description="每天重新生成日程 / Regenerate schedule daily"),
            "random_event_probability": ConfigField(type=float, default=0.1, description="随机事件触发概率 / Random event trigger probability"),
            "illness_system_enabled": ConfigField(type=bool, default=True, description="启用生病系统 / Enable illness system"),
            "illness_probability_multiplier": ConfigField(type=float, default=1.0, description="生病概率倍数 / Illness probability multiplier"),
            "auto_regenerate_on_illness": ConfigField(type=bool, default=True, description="生病时自动重新生成日程 / Auto regenerate schedule on illness"),
        },
        "time_api": {
            "method": ConfigField(type=str, default="builtin", description="时间获取方式（builtin/custom）/ Time method (builtin/custom)"),
            "url": ConfigField(type=str, default="", description="自定义时间API URL / Custom time API URL"),
            "timeout": ConfigField(type=int, default=5, description="请求超时（秒）/ Request timeout (seconds)"),
        },
        "holiday_api": {
            "enabled": ConfigField(type=bool, default=True, description="启用节日检测 / Enable holiday detection"),
            "url": ConfigField(type=str, default="https://timor.tech/api/holiday/info/{date}", description="节日API URL / Holiday API URL"),
            "cache_duration": ConfigField(type=int, default=86400, description="缓存时长（秒）/ Cache duration (seconds)"),
            "timeout": ConfigField(type=int, default=5, description="请求超时（秒）/ Request timeout (seconds)"),
        },
        "commands": {
            "enabled": ConfigField(type=bool, default=True, description="启用所有命令 / Enable all commands"),
        },
        "state": {
            "filename": ConfigField(type=str, default="state.json", description="状态保存文件名 / State save filename"),
            "auto_save_interval": ConfigField(type=int, default=300, description="自动保存间隔（秒）/ Auto-save interval (seconds)"),
        },
        "logging": {
            "level": ConfigField(type=str, default="INFO", description="日志级别 / Log level"),
            "verbose": ConfigField(type=bool, default=False, description="详细日志 / Verbose logging"),
        },
    }

    def _ensure_config_with_prompts(self):
        """确保配置文件包含提示词 / Ensure config file contains prompts"""
        config_file = Path(self.plugin_dir) / self.config_file_name

        # Check if config file exists / 检查配置文件是否存在
        if not config_file.exists():
            logger.info(f"Config file not found, creating with default prompts: {config_file}")
            self._write_default_config_with_prompts(config_file)
            return

        # Check if prompts are empty / 检查提示词是否为空
        try:
            import tomli
            with open(config_file, 'rb') as f:
                config = tomli.load(f)

            prompts_section = config.get("prompts", {})
            has_empty_prompts = any(
                not prompts_section.get(key, "").strip()
                for key in ["schedule_generation", "random_event_generation", "emotion_judgment", "habit_generation"]
            )

            if has_empty_prompts:
                logger.info(f"Config file has empty prompts, regenerating: {config_file}")
                self._write_default_config_with_prompts(config_file, existing_config=config)
        except Exception as e:
            logger.warning(f"Failed to check config file: {e}")

    def _write_default_config_with_prompts(self, config_file: Path, existing_config: Optional[Dict] = None):
        """写入包含默认提示词的配置文件 / Write config file with default prompts"""
        default_config_content = self._get_default_config_content()

        # Merge with existing config if provided / 如果提供了现有配置，则合并
        if existing_config:
            try:
                import tomli
                default_config = tomli.loads(default_config_content)
                # Merge: use existing values, but ensure prompts are from default
                # 合并：使用现有值，但确保提示词来自默认配置
                for section in default_config:
                    if section == "prompts":
                        # Always use default prompts / 总是使用默认提示词
                        existing_config[section] = default_config[section]
                    elif section not in existing_config:
                        existing_config[section] = default_config[section]

                # Convert back to TOML / 转换回 TOML
                import tomli_w
                default_config_content = tomli_w.dumps(existing_config)
            except Exception as e:
                logger.warning(f"Failed to merge config: {e}")

        # Write config file / 写入配置文件
        try:
            with open(config_file, 'w', encoding='utf-8') as f:
                f.write(default_config_content)
            logger.info(f"Config file written successfully: {config_file}")
        except Exception as e:
            logger.error(f"Failed to write config file: {e}")

    def _get_default_config_content(self) -> str:
        """获取默认配置内容 / Get default config content"""
        return '''# ============================================================
# LifeSimulationPlugin 配置文件
# Event and Human Simulation Plugin Configuration
# ============================================================
#
# 这是一个事件及人体模拟插件的配置文件
# This is the configuration file for the Event and Human Simulation Plugin
#
# 配置说明 / Configuration Notes:
# - 所有提示词都在此配置文件中 / All prompts are in this config file
# - 可以直接修改提示词内容 / You can modify prompt content directly
# - 模型配置可以指定使用哪个模型 / Model configuration can specify which model to use
# - 默认模型类型: tool_use, planner, replyer / Default model types: tool_use, planner, replyer
# - 留空表示使用系统默认模型 / Leave empty to use system default model
#
# ============================================================

# ============================================================
# [plugin] - 插件基础配置 / Basic Plugin Configuration
# ============================================================
[plugin]
# 是否启用插件 / Enable plugin
enabled = true

# 状态更新间隔（秒）/ State update interval (seconds)
# 建议：60-300秒 / Recommended: 60-300 seconds
update_interval = 60

# 数据目录 / Data directory
# 相对于插件目录 / Relative to plugin directory
data_dir = "data"

# ============================================================
# [ai] - AI模型配置 / AI Model Configuration
# ============================================================
[ai]
# 日程生成模型配置 / Schedule generation model configuration
# 留空使用 replyer 模型 / Leave empty to use replyer model
# 可选值: tool_use, planner, replyer, utils, vlm, voice, embedding, lpmm_entity_extract, lpmm_rdf_build, 或具体模型名称
# Options: tool_use, planner, replyer, utils, vlm, voice, embedding, lpmm_entity_extract, lpmm_rdf_build, or specific model name
schedule_model = "replyer"

# 随机事件生成模型配置 / Random event generation model configuration
# 留空使用 tool_use 模型 / Leave empty to use tool_use model
event_model = "tool_use"

# 情绪判断模型配置 / Emotion judgment model configuration
# 留空使用 planner 模型 / Leave empty to use planner model
emotion_model = "planner"

# 习惯生成模型配置 / Habit generation model configuration
# 留空使用 replyer 模型 / Leave empty to use replyer model
habit_model = "replyer"

# AI温度 / AI temperature
# 范围: 0.0-2.0，越高越随机 / Range: 0.0-2.0, higher means more random
temperature = 0.7

# AI最大token数 / AI max tokens
# 建议: 500-2000 / Recommended: 500-2000
max_tokens = 1000

# ============================================================
# 可用模型配置说明 / Available Model Configurations
# ============================================================
# utils - 工具模型（表情包、取名、关系、情绪等）/ Utility model (emoji, naming, relationship, emotion, etc.)
# tool_use - 工具调用模型 / Tool calling model
# replyer - 回复生成模型 / Reply generation model
# planner - 决策模型 / Decision-making model
# vlm - 图像识别模型 / Visual Language Model (image recognition)
# voice - 语音识别模型 / Voice recognition model
# embedding - 嵌入模型 / Embedding model (for knowledge base)
# lpmm_entity_extract - 实体提取模型 / Entity extraction model
# lpmm_rdf_build - RDF构建模型 / RDF building model

# ============================================================
# [prompts] - AI提示词配置 / AI Prompts Configuration
# ============================================================
[prompts]
# 日程生成提示词 / Schedule generation prompt
# 支持的变量 / Supported variables:
#   {current_time} - 当前时间 / Current time
#   {current_date} - 当前日期 / Current date
#   {day_of_week} - 星期 / Day of week
#   {is_weekend} - 是否周末 / Is weekend
#   {is_holiday} - 是否节假日 / Is holiday
#   {holiday_name} - 节日名称 / Holiday name
#   {health_status} - 健康状态 / Health status
#   {fatigue_level} - 疲劳度 / Fatigue level
#   {hunger_level} - 饥饿度 / Hunger level
#   {personality} - 人格特点 / Personality
#   {habits} - 个人习惯 / Personal habits
schedule_generation = """你是一个生活规划助手，需要为机器人生成今天的日程安排。

请根据以下信息生成一个合理的日程：
- 当前时间：{current_time}
- 当前日期：{current_date}
- 星期：{day_of_week}
- 是否周末：{is_weekend}
- 是否节假日：{is_holiday}
- 当前健康状态：{health_status}
- 当前疲劳度：{fatigue_level}/100
- 当前饥饿度：{hunger_level}/100

人格特点：
{personality}

个人习惯：
{habits}

请生成今天的日程安排，格式为JSON数组，每个元素包含：
- time: 时间（HH:MM格式）
- activity: 活动类型（work, leisure, meal, sleep, exercise, study, other, rest, medical）
- description: 活动描述（简短说明）
- priority: 优先级（1-5，5最高）

注意：
1. 日程要符合人格特点和个人习惯
2. 生病系统调整（健康度越高越健康）/ Illness system adjustment (higher health is healthier):
   - healthy (80-100): 正常日程，可安排工作、运动、娱乐 / Normal schedule, can arrange work, exercise, entertainment
   - recovering (60-79): 减少工作强度，安排康复活动 / Reduce work intensity, arrange recovery activities
   - slightly_ill (40-59): 减少工作，增加休息时间 / Reduce work, increase rest time
   - ill (20-39): 主要安排休息、轻度活动 / Mainly rest and light activities
   - seriously_ill (0-19): 只安排休息、医疗活动、必要的生活活动 / Only rest, medical activities, and essential life activities
3. 如果疲劳度高（>70），要安排更多休息 / If fatigue is high (>70), arrange more rest
4. 如果饥饿度高（>70），要优先安排用餐 / If hunger is high (>70), prioritize meals
5. 节假日可以安排更多休闲活动 / Holidays can have more leisure activities
6. 确保三餐时间合理 / Ensure reasonable meal times
7. 确保有足够的睡眠时间 / Ensure sufficient sleep time
8. 生病时可以安排医疗活动（medical）和休息活动（rest）/ When ill, can arrange medical activities and rest

请只返回JSON数组，不要有其他内容。"""

# 随机事件生成提示词 / Random event generation prompt
# 支持的变量 / Supported variables: 同上 / Same as above
random_event_generation = """你是一个生活事件生成器，需要根据当前情况生成一个随机事件。

当前情况：
- 当前时间：{current_time}
- 当前日期：{current_date}
- 星期：{day_of_week}
- 当前活动：{current_activity}
- 当前健康状态：{health_status}
- 当前疲劳度：{fatigue_level}/100
- 当前饥饿度：{hunger_level}/100

人格特点：
{personality}

请生成一个随机事件，格式为JSON对象，包含：
- event_type: 事件类型（health, social, work, leisure, emotion, other）
- event_name: 事件名称
- event_description: 事件描述（详细说明）
- health_impact: 对健康的影响（-10到10，负数表示有害，正数表示有益）
- fatigue_impact: 对疲劳的影响（-10到10）
- hunger_impact: 对饥饿的影响（-10到10）
- emotion_impact: 对情绪的影响（-10到10）
- probability: 发生概率（0.0-1.0）

注意：
1. 事件要符合当前情境
2. 事件要符合人格特点
3. 健康事件会影响健康状态，生病会导致健康度下降
4. 生病系统：当疲劳度高（>70）、饥饿度高（>70）、或情绪持续低落时，更容易产生生病事件
5. 生病类型：轻微不适（-5到-10）、生病（-10到-20）、严重生病（-20到-30）
6. 康复事件：当健康状态不佳时，可以生成康复事件（+5到+15）
7. 负面事件概率要低一些（0.05-0.2）
8. 事件描述要生动自然

生病系统说明：
- 健康度范围：0-100（越高越健康）/ Health range: 0-100 (higher is healthier)
- 健康状态 / Health status:
  * healthy (80-100): 健康 / Healthy
  * recovering (60-79): 康复中 / Recovering
  * slightly_ill (40-59): 轻微不适 / Slightly ill
  * ill (20-39): 生病 / Ill
  * seriously_ill (0-19): 严重生病 / Seriously ill
- 生病后会重新生成符合病情的日程 / Schedule will be regenerated based on illness
- 康复后会重新生成正常日程 / Schedule will be regenerated after recovery

请只返回JSON对象，不要有其他内容。"""

# 情绪判断提示词 / Emotion judgment prompt
# 支持的变量 / Supported variables: 同上 + {recent_messages} / Same as above + {recent_messages}
emotion_judgment = """你是一个情绪分析助手，需要判断机器人的当前情绪状态。

当前情况：
- 当前时间：{current_time}
- 当前日期：{current_date}
- 当前活动：{current_activity}
- 当前健康状态：{health_status}
- 当前疲劳度：{fatigue_level}/100
- 当前饥饿度：{hunger_level}/100

最近的消息：
{recent_messages}

人格特点：
{personality}

请分析机器人的当前情绪状态，格式为JSON对象，包含：
- emotion: 情绪类型（happy, sad, angry, anxious, excited, calm, tired, bored）
- intensity: 情绪强度（0-100）
- reason: 情绪原因（简短说明）

注意：
1. 情绪要符合当前情境
2. 情绪要符合人格特点
3. 考虑生理状态对情绪的影响
4. 考虑最近消息对情绪的影响
5. 情绪强度要合理

请只返回JSON对象，不要有其他内容。"""

# 习惯生成提示词 / Habit generation prompt
# 支持的变量 / Supported variables: {personality} / Personality
habit_generation = """你是一个习惯分析助手，需要根据人格特点生成个人习惯。

人格特点：
{personality}

请生成个人习惯，格式为JSON对象，包含：
- speaking_habits: 说话习惯列表（如"喜欢用表情"、"喜欢用语气词"等）
- behavior_habits: 行为习惯列表（如"早起"、"爱运动"、"爱读书"等）
- interests: 兴趣爱好列表（如"音乐"、"电影"、"游戏"、"旅行"等）
- preferences: 偏好设置（字典，包含food, music, movie等）

注意：
1. 习惯要符合人格特点
2. 习惯要多样化
3. 习惯要积极健康
4. 说话习惯要自然

请只返回JSON对象，不要有其他内容。"""

# ============================================================
# [habits] - 习惯配置 / Habits Configuration
# ============================================================
[habits]
# 是否使用AI生成习惯 / Use AI to generate habits
# true: 首次运行时AI自动生成 / true: AI generates on first run
# false: 使用下面的手动配置 / false: Use manual configuration below
use_ai_generation = true

# 手动配置习惯（仅在 use_ai_generation = false 时生效）/ Manual habits (only when use_ai_generation = false)
# 留空表示让AI生成 / Leave empty to let AI generate

# 说话习惯 / Speaking habits
speaking_habits = [
    "喜欢用表情",
    "喜欢用语气词",
    "喜欢用网络用语"
]

# 行为习惯 / Behavior habits
behavior_habits = [
    "早起",
    "爱运动",
    "爱读书"
]

# 兴趣爱好 / Interests
interests = [
    "音乐",
    "电影",
    "游戏",
    "旅行"
]

# 偏好设置 / Preferences
[habits.preferences]
# 食物偏好 / Food preference
food = "甜食"

# 音乐偏好 / Music preference
music = "流行音乐"

# 电影偏好 / Movie preference
movie = "科幻"

# ============================================================
# [schedule] - 日程配置 / Schedule Configuration
# ============================================================
[schedule]
# 是否每天重新生成日程 / Regenerate schedule daily
# true: 每天自动重新生成 / true: Auto-regenerate daily
# false: 使用上次生成的日程 / false: Use last generated schedule
regenerate_daily = true

# 随机事件触发概率 / Random event trigger probability
# 范围: 0.0-1.0 / Range: 0.0-1.0
# 0.0 = 不触发 / 0.0 = Never trigger
# 0.1 = 每小时10%概率 / 0.1 = 10% probability per hour
# 1.0 = 每小时必定触发 / 1.0 = Always trigger per hour
random_event_probability = 0.1

# 是否启用生病系统 / Enable illness system
# true: 启用生病系统，AI会根据多维度判断是否生病 / true: Enable illness system, AI judges illness based on multiple factors
# false: 禁用生病系统 / false: Disable illness system
illness_system_enabled = true

# 生病概率倍数 / Illness probability multiplier
# 范围: 0.0-2.0 / Range: 0.0-2.0
# 0.5 = 降低生病概率 / 0.5 = Reduce illness probability
# 1.0 = 正常概率 / 1.0 = Normal probability
# 2.0 = 提高生病概率 / 2.0 = Increase illness probability
illness_probability_multiplier = 1.0

# 生病时是否自动重新生成日程 / Auto regenerate schedule on illness
# true: 生病后自动重新生成符合病情的日程 / true: Auto regenerate schedule based on illness
# false: 生病后不自动重新生成日程 / false: Do not auto regenerate schedule on illness
auto_regenerate_on_illness = true

# ============================================================
# 健康状态说明 / Health Status Description
# ============================================================
# 健康度范围：0-100（越高越健康）/ Health range: 0-100 (higher is healthier)
# healthy (80-100): 健康 / Healthy
# recovering (60-79): 康复中 / Recovering
# slightly_ill (40-59): 轻微不适 / Slightly ill
# ill (20-39): 生病 / Ill
# seriously_ill (0-19): 严重生病 / Seriously ill
# 
# 生病事件会降低健康度 / Illness events reduce health
# 康复事件会提高健康度 / Recovery events increase health

# ============================================================
# [time_api] - 时间日期API配置 / Time and Date API Configuration
# ============================================================
[time_api]
# 时间日期获取方式 / Time and date method
# builtin: 使用内置datetime / builtin: Use built-in datetime
# custom: 使用自定义API / custom: Use custom API
method = "builtin"

# 自定义时间API URL (仅在 method = "custom" 时生效)/ Custom time API URL (only when method = "custom")
# 示例 / Example: "https://worldtimeapi.org/api/timezone/Asia/Shanghai"
# 需要返回JSON格式，包含 datetime 字段 / Must return JSON with datetime field
url = ""

# 自定义时间API请求超时（秒）/ Custom time API request timeout (seconds)
timeout = 5

# ============================================================
# [holiday_api] - 节日API配置 / Holiday API Configuration
# ============================================================
[holiday_api]
# 是否启用节日检测 / Enable holiday detection
enabled = true

# 节日API URL / Holiday API URL
# 默认使用 timor.tech 免费API / Default: timor.tech free API
url = "https://timor.tech/api/holiday/info/{date}"

# 节日信息缓存时长（秒）/ Holiday info cache duration (seconds)
# 默认: 86400秒（24小时）/ Default: 86400 seconds (24 hours)
cache_duration = 86400

# 请求超时（秒）/ Request timeout (seconds)
timeout = 5

# ============================================================
# [commands] - 命令配置 / Commands Configuration
# ============================================================
[commands]
# 是否启用所有命令 / Enable all commands
enabled = true

# 状态查询命令 / Status query command
[commands.status]
enabled = true
command = "/life_status"
description = "查询当前状态 / Query current status"

# 日程查询命令 / Schedule query command
[commands.schedule]
enabled = true
command = "/life_schedule"
description = "查询日程安排 / Query schedule"

# ============================================================
# [state] - 状态配置 / State Configuration
# ============================================================
[state]
# 状态保存文件名 / State save filename
# 相对于 data_dir / Relative to data_dir
filename = "state.json"

# 自动保存间隔（秒）/ Auto-save interval (seconds)
# 0 = 不自动保存 / 0 = No auto-save
# 建议: 300-600秒 / Recommended: 300-600 seconds
auto_save_interval = 300

# ============================================================
# [logging] - 日志配置 / Logging Configuration
# ============================================================
[logging]
# 日志级别 / Log level
# 可选值: DEBUG, INFO, WARNING, ERROR / Options: DEBUG, INFO, WARNING, ERROR
level = "INFO"

# 是否记录详细日志 / Enable verbose logging
verbose = false
'''

    def __init__(self, *args, **kwargs):
        global _plugin_instance
        super().__init__(*args, **kwargs)
        _plugin_instance = self

        # Check and generate config file with prompts if needed
        # 检查并生成包含提示词的配置文件（如果需要）
        self._ensure_config_with_prompts()

        # Event and task management / 事件和任务管理
        self._stop_event = asyncio.Event()
        self._scheduler_task: Optional[asyncio.Task] = None
        self._background_tasks: set[asyncio.Task] = set()
        self._tasks_lock = asyncio.Lock()

        # State management / 状态管理
        self._state = LifeState()
        self._state_lock = asyncio.Lock()

        # APIs / API
        self._time_api = TimeAPI(self.get_config("time_api", {}))
        self._holiday_api = HolidayAPI(self.get_config("holiday_api", {}))

        # Data directory / 数据目录
        plugin_dir = Path(self.plugin_dir).resolve()
        self._data_dir = plugin_dir / self.get_config("plugin.data_dir", "data")
        self._state_file = self._data_dir / self.get_config("state.filename", "state.json")
        self._data_dir.mkdir(exist_ok=True)

        logger.info("LifeSimulationPlugin initialized")

    def get_plugin_components(self) -> List[Tuple[ComponentInfo, type]]:
        """获取插件组件 / Get plugin components"""
        components = [
            # Event Handlers / 事件处理器
            (StartupHandler.get_handler_info(), StartupHandler),
            (StopHandler.get_handler_info(), StopHandler),
            (StateUpdateHandler.get_handler_info(), StateUpdateHandler),
            (MessageEventHandler.get_handler_info(), MessageEventHandler),

            # Actions / 动作
            (PerformActivityAction.get_action_info(), PerformActivityAction),
            (HandleEventAction.get_action_info(), HandleEventAction),

            # Tools / 工具
            (GetHabitsTool.get_tool_info(), GetHabitsTool),
        ]

        # Commands / 命令
        if self.get_config("commands.enabled", True):
            components.append((StatusCommand.get_command_info(), StatusCommand))
            components.append((ScheduleCommand.get_command_info(), ScheduleCommand))

        return components

    # ============================================================
    # Task Management / 任务管理
    # ============================================================

    def _create_tracked_task(self, coro, task_name: str = "unknown") -> asyncio.Task:
        """创建并跟踪后台任务 / Create and track background task"""
        async def _task_wrapper():
            try:
                logger.debug(f"Task started: {task_name}")
                return await coro
            except asyncio.CancelledError:
                logger.info(f"Task cancelled: {task_name}")
                raise
            except Exception as exc:
                logger.error(f"Task failed: {task_name}, error: {exc}", exc_info=True)
                raise

        task = asyncio.create_task(_task_wrapper())

        def _on_task_done(t: asyncio.Task):
            async def _cleanup():
                async with self._tasks_lock:
                    if t in self._background_tasks:
                        self._background_tasks.discard(t)
                        logger.debug(f"Task removed from tracking: {task_name} (remaining: {len(self._background_tasks)})")
                    if t.exception():
                        logger.warning(f"Task {task_name} completed with exception: {t.exception()}")

            try:
                loop = asyncio.get_running_loop()
                if loop.is_running():
                    cleanup_task = asyncio.create_task(_cleanup())
                    cleanup_task.add_done_callback(
                        lambda t: logger.error(f"Cleanup task failed: {t.exception()}", exc_info=True)
                        if t.exception() else None
                    )
            except RuntimeError:
                logger.warning(f"Cannot get event loop, task cleanup may fail: {task_name}")

        task.add_done_callback(_on_task_done)

        async def _add_task():
            async with self._tasks_lock:
                self._background_tasks.add(task)
                logger.debug(f"Task added to tracking: {task_name} (total: {len(self._background_tasks)})")

        try:
            loop = asyncio.get_running_loop()
            if loop.is_running():
                add_task_task = asyncio.create_task(_add_task())
                add_task_task.add_done_callback(
                    lambda t: logger.error(f"Add task failed: {t.exception()}", exc_info=True)
                    if t.exception() else None
                )
        except RuntimeError:
            logger.warning(f"Cannot get event loop, task may not be tracked: {task_name}")

        return task

    # ============================================================
    # Scheduler / 调度器
    # ============================================================

    async def start_scheduler(self):
        """启动调度器 / Start scheduler"""
        if self._scheduler_task and not self._scheduler_task.done():
            logger.warning("Scheduler already running")
            return

        logger.info("Starting life simulation scheduler")
        self._stop_event.clear()
        self._scheduler_task = self._create_tracked_task(self._scheduler_loop(), "scheduler_loop")

        # Load state / 加载状态
        await self._load_state()

        # Generate habits if not set / 如果习惯未设置，则生成
        await self._ensure_habits()

    async def stop_scheduler(self):
        """停止调度器 / Stop scheduler"""
        if not self._scheduler_task or self._scheduler_task.done():
            return

        logger.info("Stopping life simulation scheduler")
        self._stop_event.set()

        if self._scheduler_task:
            self._scheduler_task.cancel()
            try:
                await self._scheduler_task
            except asyncio.CancelledError:
                pass

        # Save state / 保存状态
        await self._save_state()

        # Cancel all background tasks / 取消所有后台任务
        async with self._tasks_lock:
            for task in self._background_tasks:
                if not task.done():
                    task.cancel()
            self._background_tasks.clear()

        logger.info("Life simulation scheduler stopped")

    async def _scheduler_loop(self):
        """调度器循环 / Scheduler loop"""
        update_interval = self.get_config("plugin.update_interval", 60)
        auto_save_interval = self.get_config("state.auto_save_interval", 300)
        last_save_time = 0

        while not self._stop_event.is_set():
            try:
                # Update states / 更新状态
                await self._update_states()

                # Auto-save / 自动保存
                current_time = datetime.now().timestamp()
                if auto_save_interval > 0 and current_time - last_save_time >= auto_save_interval:
                    await self._save_state()
                    last_save_time = current_time

                # Wait for next update / 等待下一次更新
                await asyncio.wait_for(self._stop_event.wait(), timeout=update_interval)
            except asyncio.TimeoutError:
                continue
            except Exception as e:
                logger.error(f"Scheduler loop error: {e}", exc_info=True)
                await asyncio.sleep(update_interval)

    # ============================================================
    # Prompt Management / 提示词管理
    # ============================================================

    def _get_prompt(self, prompt_type: str, **kwargs) -> str:
        """获取提示词 / Get prompt"""
        # 从配置文件获取提示词 / Get prompt from config file
        prompt = self.get_config(f"prompts.{prompt_type}", "")
        if prompt:
            return prompt.format(**kwargs)

        logger.warning(f"Prompt not found: {prompt_type}")
        return ""

    # ============================================================
    # AI Generation / AI生成
    # ============================================================

    async def _generate_schedule(self) -> List[Dict[str, Any]]:
        """生成日程 / Generate schedule"""
        try:
            now = await self._time_api.get_current_time()
            date_str = now.strftime("%Y-%m-%d")
            time_str = now.strftime("%H:%M")
            day_of_week = now.strftime("%A")
            is_weekend = now.weekday() >= 5

            # Check holiday / 检查节日
            holiday, is_holiday = await self._holiday_api.get_holiday(now.date())

            async with self._state_lock:
                self._state.current_holiday = holiday
                self._state.is_holiday = is_holiday

            # Get personality / 获取人格
            personality = self._get_personality()

            # Get habits / 获取习惯
            habits_text = await self._get_habits_text()

            # Build prompt / 构建提示词
            prompt = self._get_prompt(
                "schedule_generation",
                current_time=time_str,
                current_date=date_str,
                day_of_week=day_of_week,
                is_weekend=is_weekend,
                is_holiday=is_holiday,
                holiday_name=holiday,
                health_status=self._state.health_status.value,
                fatigue_level=self._state.fatigue,
                hunger_level=self._state.hunger,
                personality=personality,
                habits=habits_text
            )

            # Call LLM / 调用LLM
            model = self.get_config("ai.schedule_model", "replyer")
            temperature = self.get_config("ai.temperature", 0.7)
            max_tokens = self.get_config("ai.max_tokens", 1000)

            response = await llm_api.generate_with_model(
                prompt=prompt,
                model_config=model,
                temperature=temperature,
                max_tokens=max_tokens
            )

            # Parse response / 解析响应
            try:
                schedule = json.loads(response)
                if isinstance(schedule, list):
                    async with self._state_lock:
                        self._state.schedule = schedule
                        self._state.schedule_generated_date = date_str
                    logger.info(f"Generated schedule for {date_str}: {len(schedule)} activities")
                    return schedule
            except json.JSONDecodeError:
                logger.error(f"Failed to parse schedule JSON: {response}")

        except Exception as e:
            logger.error(f"Failed to generate schedule: {e}", exc_info=True)

        return []

    async def _generate_random_event(self) -> Optional[Dict[str, Any]]:
        """生成随机事件 / Generate random event"""
        try:
            now = await self._time_api.get_current_time()
            date_str = now.strftime("%Y-%m-%d")
            time_str = now.strftime("%H:%M")
            day_of_week = now.strftime("%A")

            # Get personality / 获取人格
            personality = self._get_personality()

            # Get habits / 获取习惯
            habits_text = await self._get_habits_text()

            # Build prompt / 构建提示词
            prompt = self._get_prompt(
                "random_event_generation",
                current_time=time_str,
                current_date=date_str,
                day_of_week=day_of_week,
                current_activity=self._state.current_activity,
                health_status=self._state.health_status.value,
                fatigue_level=self._state.fatigue,
                hunger_level=self._state.hunger,
                personality=personality,
                habits=habits_text
            )

            # Call LLM / 调用LLM
            model = self.get_config("ai.event_model", "tool_use")
            temperature = self.get_config("ai.temperature", 0.7)
            max_tokens = self.get_config("ai.max_tokens", 1000)

            response = await llm_api.generate_with_model(
                prompt=prompt,
                model_config=model,
                temperature=temperature,
                max_tokens=max_tokens
            )

            # Parse response / 解析响应
            try:
                event = json.loads(response)
                if isinstance(event, dict):
                    # Check probability / 检查概率
                    probability = event.get("probability", 0.0)
                    if random.random() < probability:
                        logger.info(f"Generated random event: {event.get('event_name')}")
                        return event
            except json.JSONDecodeError:
                logger.error(f"Failed to parse event JSON: {response}")

        except Exception as e:
            logger.error(f"Failed to generate random event: {e}", exc_info=True)

        return None

    async def _judge_emotion(self) -> Tuple[str, int, str]:
        """判断情绪 / Judge emotion"""
        try:
            now = await self._time_api.get_current_time()
            date_str = now.strftime("%Y-%m-%d")
            time_str = now.strftime("%H:%M")

            # Get personality / 获取人格
            personality = self._get_personality()

            # Get recent messages / 获取最近消息
            recent_messages = await self._get_recent_messages()

            # Build prompt / 构建提示词
            prompt = self._get_prompt(
                "emotion_judgment",
                current_time=time_str,
                current_date=date_str,
                current_activity=self._state.current_activity,
                health_status=self._state.health_status.value,
                fatigue_level=self._state.fatigue,
                hunger_level=self._state.hunger,
                recent_messages=recent_messages,
                personality=personality
            )

            # Call LLM / 调用LLM
            model = self.get_config("ai.emotion_model", "planner")
            temperature = self.get_config("ai.temperature", 0.7)
            max_tokens = self.get_config("ai.max_tokens", 500)

            response = await llm_api.generate_with_model(
                prompt=prompt,
                model_config=model,
                temperature=temperature,
                max_tokens=max_tokens
            )

            # Parse response / 解析响应
            try:
                emotion_data = json.loads(response)
                if isinstance(emotion_data, dict):
                    emotion = emotion_data.get("emotion", "calm")
                    intensity = emotion_data.get("intensity", 0)
                    reason = emotion_data.get("reason", "")

                    async with self._state_lock:
                        self._state.current_emotion = emotion
                        self._state.emotion_intensity = intensity
                        self._state.emotion_reason = reason

                    return emotion, intensity, reason
            except json.JSONDecodeError:
                logger.error(f"Failed to parse emotion JSON: {response}")

        except Exception as e:
            logger.error(f"Failed to judge emotion: {e}", exc_info=True)

        return "calm", 0, ""

    async def _generate_habits(self) -> bool:
        """生成习惯 / Generate habits"""
        try:
            # Get personality / 获取人格
            personality = self._get_personality()

            # Build prompt / 构建提示词
            prompt = self._get_prompt("habit_generation", personality=personality)

            # Call LLM / 调用LLM
            model = self.get_config("ai.habit_model", "replyer")
            temperature = self.get_config("ai.temperature", 0.7)
            max_tokens = self.get_config("ai.max_tokens", 500)

            response = await llm_api.generate_with_model(
                prompt=prompt,
                model_config=model,
                temperature=temperature,
                max_tokens=max_tokens
            )

            # Parse response / 解析响应
            try:
                habits_data = json.loads(response)
                if isinstance(habits_data, dict):
                    async with self._state_lock:
                        self._state.speaking_habits = habits_data.get("speaking_habits", [])
                        self._state.behavior_habits = habits_data.get("behavior_habits", [])
                        self._state.interests = habits_data.get("interests", [])
                        self._state.preferences = habits_data.get("preferences", {})

                    logger.info("Generated habits successfully")
                    return True
            except json.JSONDecodeError:
                logger.error(f"Failed to parse habits JSON: {response}")

        except Exception as e:
            logger.error(f"Failed to generate habits: {e}", exc_info=True)

        return False

    # ============================================================
    # Helper Methods / 辅助方法
    # ============================================================

    def _get_personality(self) -> str:
        """获取人格描述 / Get personality description"""
        try:
            from src.config.config import global_config
            personality_file = global_config.get("personality.personality_file", "")
            if personality_file and os.path.exists(personality_file):
                with open(personality_file, 'r', encoding='utf-8') as f:
                    return f.read()[:500]  # Limit to 500 chars
        except Exception as e:
            logger.warning(f"Failed to read personality file: {e}")
        return "一个友好、开朗的AI助手"

    async def _get_habits_text(self) -> str:
        """获取习惯文本 / Get habits text"""
        async with self._state_lock:
            habits_list = []
            if self._state.speaking_habits:
                habits_list.append(f"说话习惯: {', '.join(self._state.speaking_habits)}")
            if self._state.behavior_habits:
                habits_list.append(f"行为习惯: {', '.join(self._state.behavior_habits)}")
            if self._state.interests:
                habits_list.append(f"兴趣爱好: {', '.join(self._state.interests)}")
            return "\n".join(habits_list) if habits_list else "暂无习惯"

    async def _get_recent_messages(self) -> str:
        """获取最近消息 / Get recent messages"""
        try:
            messages = await message_api.get_recent_messages(chat_id="*", hours=1, limit=5)
            if messages:
                return "\n".join([f"{msg.get('sender', 'Unknown')}: {msg.get('content', '')}" for msg in messages])
        except Exception as e:
            logger.warning(f"Failed to get recent messages: {e}")
        return "暂无最近消息"

    async def _ensure_habits(self):
        """确保习惯已设置 / Ensure habits are set"""
        use_ai_generation = self.get_config("habits.use_ai_generation", True)

        async with self._state_lock:
            has_habits = (
                self._state.speaking_habits or
                self._state.behavior_habits or
                self._state.interests
            )

        if not has_habits and use_ai_generation:
            await self._generate_habits()
        elif not has_habits:
            # Load from config / 从配置加载
            async with self._state_lock:
                self._state.speaking_habits = self.get_config("habits.speaking_habits", [])
                self._state.behavior_habits = self.get_config("habits.behavior_habits", [])
                self._state.interests = self.get_config("habits.interests", [])

    # ============================================================
    # State Management / 状态管理
    # ============================================================

    async def _update_states(self):
        """更新状态 / Update states"""
        async with self._state_lock:
            current_time = await self._time_api.get_current_time()
            date_str = current_time.strftime("%Y-%m-%d")
            time_delta = current_time.timestamp() - self._state.last_update if self._state.last_update > 0 else 0

            if time_delta < 60:  # Only update if at least 1 minute has passed
                return

        # Check if need to regenerate schedule / 检查是否需要重新生成日程
        regenerate_daily = self.get_config("schedule.regenerate_daily", True)
        if regenerate_daily and self._state.schedule_generated_date != date_str:
            await self._generate_schedule()

        # Check for random events / 检查随机事件
        random_event_probability = self.get_config("schedule.random_event_probability", 0.1)
        if random.random() < random_event_probability:
            event = await self._generate_random_event()
            if event:
                await self._handle_event(event)

        # Judge emotion / 判断情绪
        await self._judge_emotion()

        async with self._state_lock:
            self._state.last_update = current_time.timestamp()

    async def _handle_event(self, event: Dict[str, Any]):
        """处理事件 / Handle event"""
        try:
            # Apply impacts / 应用影响
            health_impact = event.get("health_impact", 0)
            fatigue_impact = event.get("fatigue_impact", 0)
            hunger_impact = event.get("hunger_impact", 0)
            emotion_impact = event.get("emotion_impact", 0)

            old_health_status = self._state.health_status

            async with self._state_lock:
                self._state.health = max(0, min(100, self._state.health + health_impact))
                self._state.fatigue = max(0, min(100, self._state.fatigue + fatigue_impact))
                self._state.hunger = max(0, min(100, self._state.hunger + hunger_impact))
                self._state.emotion_intensity = max(0, min(100, self._state.emotion_intensity + emotion_impact))

                # Update health status / 更新健康状态
                # 健康度越高越健康 / Higher health value means healthier
                if self._state.health >= 80:
                    self._state.health_status = HealthStatus.HEALTHY
                elif self._state.health >= 60:
                    self._state.health_status = HealthStatus.RECOVERING
                elif self._state.health >= 40:
                    self._state.health_status = HealthStatus.SLIGHTLY_ILL
                elif self._state.health >= 20:
                    self._state.health_status = HealthStatus.ILL
                else:
                    self._state.health_status = HealthStatus.SERIOUSLY_ILL

            # Check if health status changed / 检查健康状态是否变化
            new_health_status = self._state.health_status
            if old_health_status != new_health_status:
                logger.info(f"Health status changed: {old_health_status.value} -> {new_health_status.value}")

                # If became ill, regenerate schedule based on new health status
                # 如果生病了，根据新的健康状态重新生成日程
                if new_health_status != HealthStatus.HEALTHY:
                    logger.info(f"Regenerating schedule due to illness: {new_health_status.value}")
                    await self._generate_schedule()
                # If recovered, regenerate schedule
                # 如果康复了，重新生成日程
                elif old_health_status != HealthStatus.HEALTHY:
                    logger.info("Regenerating schedule after recovery")
                    await self._generate_schedule()

            logger.info(f"Handled event: {event.get('event_name')}, impacts: health={health_impact}, fatigue={fatigue_impact}, hunger={hunger_impact}, emotion={emotion_impact}")
        except Exception as e:
            logger.error(f"Failed to handle event: {e}", exc_info=True)

    async def _save_state(self):
        """保存状态 / Save state"""
        try:
            state_data = self._state.to_dict()
            with open(self._state_file, 'w', encoding='utf-8') as f:
                json.dump(state_data, f, indent=2, ensure_ascii=False)
        except Exception as e:
            logger.error(f"Failed to save state: {e}", exc_info=True)

    async def _load_state(self):
        """加载状态 / Load state"""
        try:
            if self._state_file.exists():
                with open(self._state_file, 'r', encoding='utf-8') as f:
                    state_data = json.load(f)
                self._state.from_dict(state_data)
                logger.info("State loaded successfully")
        except Exception as e:
            logger.error(f"Failed to load state: {e}", exc_info=True)

    # ============================================================
    # Public API / 公共API
    # ============================================================

    async def get_state(self) -> Dict[str, Any]:
        """获取状态 / Get state"""
        async with self._state_lock:
            return self._state.to_dict()


# ============================================================
# Event Handlers / 事件处理器
# ============================================================

class StartupHandler(BaseEventHandler):
    """启动事件处理器 / Startup Event Handler"""

    event_type = EventType.ON_START
    handler_name = "life_simulation_startup"
    handler_description = "Start life simulation scheduler / 启动生活模拟调度器"

    async def execute(self, message: MaiMessages | None) -> Tuple[bool, bool, Optional[str], None, None]:
        if _plugin_instance:
            await _plugin_instance.start_scheduler()
            return True, True, "生活模拟插件已启动", None, None
        return True, True, None, None, None


class StopHandler(BaseEventHandler):
    """停止事件处理器 / Stop Event Handler"""

    event_type = EventType.ON_STOP
    handler_name = "life_simulation_stop"
    handler_description = "Stop life simulation scheduler / 停止生活模拟调度器"

    async def execute(self, message: MaiMessages | None) -> Tuple[bool, bool, Optional[str], None, None]:
        if _plugin_instance:
            await _plugin_instance.stop_scheduler()
            return True, True, "生活模拟插件已停止", None, None
        return True, True, None, None, None


class StateUpdateHandler(BaseEventHandler):
    """状态更新事件处理器 / State Update Event Handler"""

    event_type = EventType.ON_START
    handler_name = "life_simulation_state_update"
    handler_description = "Update states periodically / 定期更新状态"

    async def execute(self, message: MaiMessages | None) -> Tuple[bool, bool, Optional[str], None, None]:
        # State updates are handled by the scheduler loop
        # 状态更新由调度器循环处理
        return True, True, None, None, None


class MessageEventHandler(BaseEventHandler):
    """消息事件处理器 / Message Event Handler"""

    event_type = EventType.ON_MESSAGE
    handler_name = "life_simulation_message"
    handler_description = "Process message events / 处理消息事件"
    weight = 10

    async def execute(self, message: MaiMessages | None) -> Tuple[bool, bool, Optional[str], None, None]:
        if not _plugin_instance or not message:
            return True, True, None, None, None

        # Slight increase in fatigue and hunger on message with probability
        # 消息时按概率略微增加疲劳度和饥饿度
        import random

        update_probability = _plugin_instance._config.get("message_state_update_probability", 0.7)
        if random.random() < update_probability:
            async with _plugin_instance._state_lock:
                _plugin_instance._state.fatigue = min(100, _plugin_instance._state.fatigue + 1)
                _plugin_instance._state.hunger = min(100, _plugin_instance._state.hunger + 1)

        return True, True, None, None, None


# ============================================================
# Actions / 动作
# ============================================================

class PerformActivityAction(BaseAction):
    """执行活动动作 / Perform Activity Action"""

    action_name = "perform_activity"
    action_description = "执行日程中的活动 / Perform scheduled activity"
    activation_type = ActionActivationType.ALWAYS
    associated_types = ["text"]
    parallel_action = False

    action_parameters = {
        "activity": "活动信息 / Activity information",
        "description": "活动描述 / Activity description"
    }
    action_require = [
        "需要执行日程中的活动时使用 / Use when performing scheduled activity",
        "需要开始新的活动时使用 / Use when starting new activity"
    ]

    async def execute(self) -> Tuple[bool, str]:
        if not _plugin_instance:
            return False, "插件未就绪"

        try:
            activity = self.action_data.get("activity", "")
            description = self.action_data.get("description", "")

            async with _plugin_instance._state_lock:
                _plugin_instance._state.current_activity = activity
                _plugin_instance._state.current_activity_description = description
                _plugin_instance._state.last_activity_time = (await _plugin_instance._time_api.get_current_time()).timestamp()

            # Generate AI response about the activity
            # 生成关于活动的AI响应
            # Note: The response should be generated by AI, not fixed
            # 注意：响应应该由AI生成，不固定
            response = f"开始{description}" if description else f"开始{activity}"

            await self.send_text(response)

            return True, "动作已完成"
        except Exception as e:
            logger.error(f"PerformActivityAction failed: {e}", exc_info=True)
            return False, str(e)


class HandleEventAction(BaseAction):
    """处理事件动作 / Handle Event Action"""

    action_name = "handle_event"
    action_description = "处理随机事件 / Handle random event"
    activation_type = ActionActivationType.ALWAYS
    associated_types = ["text"]
    parallel_action = False

    action_parameters = {
        "event": "事件信息 / Event information"
    }
    action_require = [
        "需要处理随机事件时使用 / Use when handling random event",
        "事件发生时使用 / Use when event occurs"
    ]

    async def execute(self) -> Tuple[bool, str]:
        if not _plugin_instance:
            return False, "插件未就绪"

        try:
            event = self.action_data.get("event", {})
            event_name = event.get("event_name", "")
            event_description = event.get("event_description", "")

            # Handle the event impacts
            # 处理事件影响
            await _plugin_instance._handle_event(event)

            # Generate AI response about the event
            # 生成关于事件的AI响应
            # Note: The response should be generated by AI, not fixed
            # 注意：响应应该由AI生成，不固定
            response = event_description if event_description else f"发生了{event_name}"

            await self.send_text(response)

            return True, "动作已完成"
        except Exception as e:
            logger.error(f"HandleEventAction failed: {e}", exc_info=True)
            return False, str(e)


# ============================================================
# Commands / 命令
# ============================================================

class StatusCommand(BaseCommand):
    """状态查询命令 / Status Query Command"""

    command_name = "life_status"
    command_description = "查询当前状态 / Query current status"
    command_pattern = r"^/life_status$"

    async def execute(self) -> Tuple[bool, Optional[str], int]:
        if not _plugin_instance:
            await self.send_text("插件未就绪", storage_message=False)
            return False, None, 0

        if not _plugin_instance.get_config("commands.enabled", True):
            await self.send_text("命令已禁用", storage_message=False)
            return False, None, 0

        try:
            state = await _plugin_instance.get_state()

            # Build status message / 构建状态消息
            status_msg = f"""📊 当前状态：

😴 睡眠状态: {state['sleep_state']}
😫 疲劳度: {state['fatigue']}/100
🍔 饥饿度: {state['hunger']}/100
❤️ 健康度: {state['health']}/100 ({state['health_status']})
😊 情绪: {state['current_emotion']} ({state['emotion_intensity']}/100)
🏃 当前活动: {state['current_activity']} - {state['current_activity_description']}
🎉 节日: {state['current_holiday'] if state['current_holiday'] else '无'}"""

            await self.send_text(status_msg, storage_message=False)
            return True, None, 1
        except Exception as e:
            logger.error(f"StatusCommand failed: {e}", exc_info=True)
            await self.send_text(f"操作失败: {str(e)}", storage_message=False)
            return False, None, 0


class ScheduleCommand(BaseCommand):
    """日程查询命令 / Schedule Query Command"""

    command_name = "life_schedule"
    command_description = "查询日程安排 / Query schedule"
    command_pattern = r"^/life_schedule$"

    async def execute(self) -> Tuple[bool, Optional[str], int]:
        if not _plugin_instance:
            await self.send_text("插件未就绪", storage_message=False)
            return False, None, 0

        if not _plugin_instance.get_config("commands.enabled", True):
            await self.send_text("命令已禁用", storage_message=False)
            return False, None, 0

        try:
            state = await _plugin_instance.get_state()
            schedule = state.get("schedule", [])

            # Build schedule message / 构建日程消息
            if schedule:
                schedule_msg = f"📅 日程安排 ({state['schedule_generated_date']}):\n\n"
                for item in schedule:
                    time_str = item.get("time", "")
                    activity = item.get("activity", "")
                    description = item.get("description", "")
                    priority = item.get("priority", 0)
                    schedule_msg += f"⏰ {time_str} - {activity} ({description}) [优先级: {priority}]\n"
            else:
                schedule_msg = "📅 日程安排: 暂无日程"

            await self.send_text(schedule_msg, storage_message=False)
            return True, None, 1
        except Exception as e:
            logger.error(f"ScheduleCommand failed: {e}", exc_info=True)
            await self.send_text(f"操作失败: {str(e)}", storage_message=False)
            return False, None, 0


# ============================================================
# Tools / 工具
# ============================================================

class GetHabitsTool(BaseTool):
    """获取习惯工具 / Get Habits Tool"""

    name = "get_life_simulation_habits"
    description = "获取生活模拟插件中的个人习惯信息，包括说话习惯、行为习惯、兴趣爱好和偏好设置"
    parameters = []
    available_for_llm = True

    async def execute(self, function_args: dict[str, Any]) -> dict[str, Any]:
        """执行工具 / Execute tool"""
        try:
            if not _plugin_instance:
                return {
                    "name": self.name,
                    "content": "生活模拟插件未就绪",
                    "error": "Plugin not ready"
                }

            state = await _plugin_instance.get_state()

            # 构建习惯信息 / Build habits information
            habits_info = {
                "speaking_habits": state.get("speaking_habits", []),
                "behavior_habits": state.get("behavior_habits", []),
                "interests": state.get("interests", []),
                "preferences": state.get("preferences", {})
            }

            # 格式化为文本 / Format as text
            habits_text = []
            if habits_info["speaking_habits"]:
                habits_text.append(f"说话习惯: {', '.join(habits_info['speaking_habits'])}")
            if habits_info["behavior_habits"]:
                habits_text.append(f"行为习惯: {', '.join(habits_info['behavior_habits'])}")
            if habits_info["interests"]:
                habits_text.append(f"兴趣爱好: {', '.join(habits_info['interests'])}")
            if habits_info["preferences"]:
                prefs_text = ", ".join([f"{k}: {v}" for k, v in habits_info["preferences"].items()])
                habits_text.append(f"偏好设置: {prefs_text}")

            if not habits_text:
                habits_text.append("暂无习惯信息")

            return {
                "name": self.name,
                "content": "\n".join(habits_text),
                "habits": habits_info
            }
        except Exception as e:
            logger.error(f"GetHabitsTool failed: {e}", exc_info=True)
            return {
                "name": self.name,
                "content": f"获取习惯信息失败: {str(e)}",
                "error": str(e)
            }